### ISSUE TITLE
Minecraft crashing when loading with Spell Bundle

### ISSUE THREAD

**Issue by ipdnaeip** [WinDanesz/SpellBundle#1]
I added Spell Bundle to my minecraft modpack and was able to start the game. After I loaded in and tried creating a new world, the world generation got stuck on 0% and crashed after minute. I now get an error message in the launcher. 

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/blay09/mods/waystones/WarpMode
Exit Code: -1

The modpack was able to run without Spell Bundle installed.

**Comment by WinDanesz** [comment]
I'll release an update soon to fix this, but Spell Bundle currently only adds support stuff for the Waystones mod. That means without Waystones, you won't have anything useful from Spell Bundle. Still not a good thing to crash so I'm fixing that, it will matter more after support is added for the next optional mod.

**Comment by WinDanesz** [comment]
fixed in 1.0.1
