### ISSUE TITLE
[Bug] Conjure Foxhound asset/json file is still showing as Advanced instead of Apprentice

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/SpellBundle#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

When looking at the Conjure_Foxhound json within the Spell Bundle asset folder, it is still showing as Advanced Tier.

"tier": "advanced"

### Expected behaviour

Since the Changelog reports "Lowered Summon Foxhound spell tier Advanced->Apprentice", I would have expected it to be Apprentice tier.

### Steps to reproduce

1. Download the latest Spell Bundle
2. Open the jar file and look at assets/spells/Conjure_Foxhound
3. Note the tier listed.

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.5.7

### Forge version

1.12.2-forge-14.23.5.2860

**Comment by KnightCa** [comment]
Also consider adding the newly created spell/artifact to the Spell Bundle description page ;)

**Comment by WinDanesz** [comment]
Done, thanks

**Comment by KnightCa** [comment]
Anytime ;)
