### ISSUE TITLE
[Bug] Frozen Lock bauble charm does not allow Ice Chests (from the spell) to be locked

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/SpellBundle#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

While wearing the Frozen Lock bauble charm, I am unable to lock a Ice Chest (summoned via the Ice Chest spell).

### Expected behaviour

I expected that while wearing the Frozen Lock bauble, I would ne able to interact with a Ice Chest the same way that I would with a normal Treasure2 treasure chest (either casting the Lock spell or applying Treasure2 locks).

### Steps to reproduce

1. Join a Server with the mods Spell Bundle (and Electroblob Wizardry) and Treasure2 (with both Wizardry Loot Pack and GottschCore)
2. Cast Ice Chest with a Master Ice Wand
3. Put on the Frozen Lock bauble charm
4. Try sneak-casting Lock on the Ice Chest (note the lack of any spectral locks)
5. Try sneak-right clicking with a wood, stone, iron, and gold lock from Treasure2 (likewise no effect)

### Environment (Singleplayer/Server, etc.)

Singleplayer

### Mod version

1.1.4

### Forge version

1.12.2-forge-14.23.5.2860

### Other mods

Treasure2: mc1.12.2-f14.23.5.2859-v2.2.0
Treasure2 Wizardry Loot Pack: f14.23.5.2859-v2.0.0
GottschCore: mc1.12.2-f14.23.5.2859-v1.15.0

**Comment by WinDanesz** [comment]
This is intended, the Ice Chest is not a lockable chest.

**Comment by KnightCa** [comment]
![image](https://github.com/WinDanesz/SpellBundle/assets/51968609/1c399184-5835-4f57-9540-8ca3148612df)

**Comment by WinDanesz** [comment]
Yeah, it must be bugged
